Fix a bug where the HTML version of the manuals was not being installed
Branches: main
Estimated hours taken: 1.5

Fix a bug where the HTML version of the manuals was not being installed
on the web page.

w3/information/Makefile:
	When copying the HTML documentation, make sure that we copy the
	mercury_ref, mercury_user_guide, etc. subdirectories that are
	generated by "makeinfo --html".

	Also, use "&&" rather than ";" to ensure that failures are not
	silently ignored.

diff --git a/information/Makefile b/information/Makefile
--- a/information/Makefile
+++ b/information/Makefile
@@ -52,16 +52,27 @@ local:
 	for branch in release latest; do \
 		info_dir=`pwd`; \
 		doc_dir=$$info_dir/doc-$$branch; \
-		cd mercury-$$branch/mercury; \
-		echo "LIBRARY_DIR=`pwd`/library"  > Mmake.common; \
-		echo "PERL=perl"  >> Mmake.common; \
-		echo "INFO=info"  >> Mmake.common; \
-		echo "DVIPS=dvips"  >> Mmake.common; \
-		echo 'include $$(MERCURY_DIR)/VERSION'  >> Mmake.common; \
-		(cd doc; mmake split_html ps); \
-		$(CP) doc/*.html doc/*.ps $$doc_dir; \
-		(cd $$doc_dir; gzip -f -9 *.ps); \
-		cd $$info_dir; \
+		cd mercury-$$branch/mercury && \
+		echo "LIBRARY_DIR=`pwd`/library"  > Mmake.common && \
+		echo "PERL=perl"  >> Mmake.common && \
+		echo "INFO=info"  >> Mmake.common && \
+		echo "DVIPS=dvips"  >> Mmake.common && \
+		echo 'include $$(MERCURY_DIR)/VERSION'  >> Mmake.common && \
+		(cd doc && mmake split_html ps) && \
+		$(CP) doc/*.html doc/*.ps $$doc_dir && \
+		if [ -d doc/mercury_ref ]; then \
+		    	$(CP) doc/mercury_ref doc/mercury_user_guide \
+				doc/mercury_library doc/mercury_faq \
+				doc/mercury_trans_guide \
+				$$doc_dir; \
+		else \
+			true; \
+		fi && \
+		(cd $$doc_dir && gzip -f -9 *.ps) && \
+		cd $$info_dir || { \
+			echo "*** copying documentation failed" 1>&2; \
+			exit 1; \
+		} \
 	done
 	# It's not worth installing the release branch versions of
 	# these files. Developers should normally be working with
